### ISSUE TITLE
少上传了timer.py？

### ISSUE THREAD

**Issue by xjt1995** [chao325/QmaoTai#1]

**Comment by cuijianzhuang** [comment]
确实是少了，自己加上就行了

**Comment by chao325** [comment]
原作者的timer有问题，并不能和JD服务器时间同步哈。而且抢购也没有更新Tik

**Comment by cuijianzhuang** [comment]
![image](https://github.com/chao325/QmaoTai/assets/31424401/1a3e0922-d1c1-4cf9-8c06-2f46f2e65727)
作者这个咋解决
